services:
  {{project-name}}:
    build:
      context: .
      dockerfile: Dockerfile
    image: "ghcr.io/baker-link-lab/bakerlink-env:latest"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - "../:/{{project-name}}"
    working_dir: /{{project-name}}
    command: sleep infinity
